# -----------------------------------------------------------------------------
# MantisBT GitHub Actions Worflow to run PHPUnit tests
# -----------------------------------------------------------------------------

name: MantisBT unit tests
on:
  push:
    branches:
    - master
    - "master-[0-9]+.[0-9]+"
    - "**"
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Tests:
    name: PHP ${{ matrix.php }} on ${{ matrix.DB }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        DB:
          - mysql
          - pgsql
        php:
          - 8.3
          - 8.2
          - 8.1
          - 8.0
          - 7.4
          # 'allow_failures' transformations are currently unsupported.

    env:
      DB: "${{ matrix.DB }}"

    steps:
    - uses: shivammathur/setup-php@2.29.0
      # https://setup-php.com/
      with:
        php-version: "${{ matrix.php }}"
        tools: phpunit
        ini-values: |
          sendmail_path=${{ github.workspace }}/tests/fakesendmail.sh

    - name: checkout
      uses: actions/checkout@v4.1.0

    - run: composer install

    - run: "./build/travis_before_script.sh"

    - run: "./build/travis_script.sh"

    services:
      postgresql:
        image: postgres
      mysql:
        image: mysql

  Documentation:
    runs-on: ubuntu-20.04
    env:
      DOCBOOK: '1'
      DB: mysql
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - run: apt-get -y install publican
    - run: composer install
    - run: "./build/travis_before_script.sh"
    - run: "./build/travis_script.sh"
    services:
      postgresql:
        image: postgres
      mysql:
        image: mysql
